language: rust
rust:
  - stable

env:
  global:
    - RUST_BACKTRACE="1"
    - CXX="g++-4.8"
    - CC="gcc-4.8"
  matrix:
    - TEST_DIR=core
    - TEST_DIR=p2p
    - TEST_DIR=chain
    - TEST_DIR=grin

script: cd $TEST_DIR && cargo test --verbose
