[package]
name = "grin"
version = "0.1.0"
authors = ["Ignotus Peverell <igno.peverell@protonmail.com>"]

[workspace]
members = ["api", "chain", "core", "grin", "p2p", "store", "util", "pool"]

[dependencies]
grin_grin = { path = "./grin" }

clap = "^2.23.3"
daemonize = "^0.2.3"
env_logger="^0.3.5"
log = "^0.3"
serde = "~0.9.10"
serde_json = "~0.9.9"
