[package]
name = "grin"
version = "0.1.0"
authors = ["Ignotus Peverell <igno.peverell@protonmail.com>"]

[dependencies]
grin_chain = { path = "../chain" }
grin_core = { path = "../core" }
grin_store = { path = "../store" }
secp256k1zkp = { path = "../secp256k1zkp" }

env_logger="^0.3.5"
log = "^0.3"
time = "^0.1"
rand = "^0.3"
