[package]
name = "grin_store"
version = "0.1.0"
authors = ["Ignotus Peverell <igno.peverell@protonmail.com>"]

[dependencies]
rocksdb = { git = "https://github.com/ethcore/rust-rocksdb" }
tiny-keccak = "1.1"

grin_core = { path = "../core" }
