[package]
name = "grin_store"
version = "0.1.0"
authors = ["Ignotus Peverell <igno.peverell@protonmail.com>"]
workspace = ".."

[dependencies]
byteorder = "^0.5"
env_logger="^0.3.5"
log = "^0.3"
memmap = { git = "https://github.com/danburkert/memmap-rs" }
rocksdb = "^0.7.0"

grin_core = { path = "../core" }

[dev-dependencies]
env_logger="^0.3.5"
time = "^0.1"
