[package]
name = "grin_servers"
version = "3.2.2"
authors = ["Grin Developers <mimblewimble@lists.launchpad.net>"]
description = "Simple, private and scalable cryptocurrency implementation based on the MimbleWimble chain format."
license = "Apache-2.0"
repository = "https://github.com/mimblewimble/grin"
keywords = [ "crypto", "grin", "mimblewimble" ]
workspace = ".."
edition = "2018"

[dependencies]
hyper = "0.13"
fs2 = "0.4"
futures = "0.3"
http = "0.1"
lmdb-zero = "0.4.4"
rand = "0.6"
serde = "1"
log = "0.4"
serde_derive = "1"
serde_json = "1"
chrono = "0.4.4"
tokio = {version = "0.2", features = ["full"] }
tokio-util = { version = "0.2", features = ["codec"] }
walkdir = "2.2.9"
failure = "0.1"
failure_derive = "0.1"

grin_api = { path = "../api", version = "3.2.2" }
grin_chain = { path = "../chain", version = "3.2.2" }
grin_core = { path = "../core", version = "3.2.2" }
grin_keychain = { path = "../keychain", version = "3.2.2" }
grin_p2p = { path = "../p2p", version = "3.2.2" }
grin_pool = { path = "../pool", version = "3.2.2" }
grin_store = { path = "../store", version = "3.2.2" }
grin_util = { path = "../util", version = "3.2.2" }


[target.'cfg(not(target_os = "android"))'.dependencies]
hyper-rustls = "0.19"

[target.'cfg(target_os = "android")'.dependencies]
hyper-rustls = { version = "0.20", default-features = false, features = ["webpki-tokio"] }
