[package]
name = "grin_api"
version = "0.1.0"
authors = ["Ignotus Peverell <igno.peverell@protonmail.com>"]
workspace = ".."

[dependencies]
grin_chain = { path = "../chain" }

hyper = "~0.10.6"
iron = "~0.5.1"
log = "~0.3"
router = "~0.5.1"
serde = "~0.9.10"
serde_json = "~0.9.8"
